# Generated by Django 2.2.5 on 2019-11-23 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('didgUwear', '0002_auto_20191117_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pant',
            old_name='date',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='date',
            new_name='date_added',
        ),
    ]
