# Generated by Django 2.2.5 on 2019-10-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
                ('style', models.CharField(max_length=30, null=True)),
                ('pattern', models.CharField(max_length=30, null=True)),
                ('texture', models.CharField(max_length=30, null=True)),
                ('season', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('img', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
                ('style', models.CharField(max_length=30, null=True)),
                ('pattern', models.CharField(max_length=30, null=True)),
                ('texture', models.CharField(max_length=30, null=True)),
                ('season', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('img', models.CharField(max_length=50)),
            ],
        ),
    ]
