# Generated by Django 2.2.5 on 2019-11-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didgUwear', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pant',
            old_name='pattern',
            new_name='fit',
        ),
        migrations.RenameField(
            model_name='pant',
            old_name='texture',
            new_name='holiday',
        ),
        migrations.RenameField(
            model_name='pant',
            old_name='img',
            new_name='img_link',
        ),
        migrations.RenameField(
            model_name='pant',
            old_name='color',
            new_name='occasion',
        ),
        migrations.RenameField(
            model_name='pant',
            old_name='season',
            new_name='primary_color',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='pattern',
            new_name='fit',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='texture',
            new_name='holiday',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='img',
            new_name='img_link',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='color',
            new_name='occasion',
        ),
        migrations.RenameField(
            model_name='shirt',
            old_name='season',
            new_name='primary_color',
        ),
        migrations.AddField(
            model_name='pant',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pant',
            name='secondary_color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pant',
            name='weather',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shirt',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shirt',
            name='secondary_color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='shirt',
            name='weather',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pant',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pant',
            name='style',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='style',
            field=models.CharField(max_length=30),
        ),
    ]
